apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admins-role
subjects:
  # Allows anyone in the "GKE-Admins" group full admin access
- kind: Group
  name: GKE-Admins # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
  #- kind: User
  #name: ddmc
  #apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin-all
  apiGroup: rbac.authorization.k8s.io
